fix: foundation of breaking circular dependencies
ocadotechnology/codeforlife-package-python pull request #17
Opened 2023-10-23 08:34 UTC by SKairinos

2023-10-23 12:08 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17)* status: 0 of 38 files reviewed, 5 unresolved discussions

___
*[`codeforlife/pagination.py` line 9 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRLQTQ8AZl59tR58J2:-NhRLQTQ8AZl59tR58J3:b2ngy1z) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/pagination.py#L9)):*
> ```Python
> class LimitOffsetPagination(_LimitOffsetPagination):
>     default_limit = 50
>     max_limit = 500
> ```

150
___
*[`codeforlife/tests/api.py` line 208 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRQvYF3JZml_YtFjgk:-NhRQvYF3JZml_YtFjgl:b-civv1t) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/tests/api.py#L208)):*
> ```Python
>     ):
>         """
>         Get a different user that is also in a school.
> ```

clearer doc strings
___
*[`codeforlife/user/filters/user.py` line 8 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRISQ3AgKN2hj0lajp:-NhRISQ3AgKN2hj0lajq:b-bhb4b) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/filters/user.py#L8)):*
> ```Python
> class UserFilterSet(filters.FilterSet):
>     students_in_class = filters.CharFilter(
>         "new_student__class_field__access_code", "exact"
> ```

use new_student__class_field
___
*[`codeforlife/user/views/user.py` line 16 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRHhuTADE3MvqtoXVK:-NhRHhuTADE3MvqtoXVL:b-q70vh5) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/views/user.py#L16)):*
> ```Python
>         user: User = self.request.user
>         if user.teacher is None:
>             return User.objects.filter(id=user.id)
> ```

students can read all other students in their class 
___
*[`codeforlife/user/views/user.py` line 21 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRHNdI0_mDF1TvBtY7:-NhRHNdI0_mDF1TvBtY8:b2wx4xq) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/views/user.py#L21)):*
> ```Python
>             new_teacher__school=user.teacher.school_id
>         )
>         students = User.objects.filter(
> ```

if admin, all students in all classes
else, all students in classes teacher owns


<!-- Sent from Reviewable.io -->

2023-10-23 13:44 UTC, faucomte97 requested changes
> Reviewed 5 of 17 files at r1, 1 of 1 files at r2, 32 of 32 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17)* status: all files reviewed, 41 unresolved discussions (waiting on @SKairinos)

___
*[`codeforlife/pagination.py` line 9 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRLQTQ8AZl59tR58J2:-NhRcRHU0qXK1CAaC2a6:bsoodxz) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/pagination.py#L9)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

150
</blockquote></details>

Reminder
___
*[`codeforlife/settings/django.py` line 127 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRcg8r4J0Sc3qXli7g:-NhRcg8r4J0Sc3qXli7h:bizinxn) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/settings/django.py#L127)):*
> ```Python
> 
> # Installed Apps
> # https://docs.djangoproject.com/en/4.2/ref/settings/#installed-apps
> ```

Wrong Django version
___
*[`codeforlife/tests/api.py` line 208 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRQvYF3JZml_YtFjgk:-NhRfSHf1le6HB8Umk8Y:bsoodxz) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/tests/api.py#L208)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

clearer doc strings
</blockquote></details>

Reminder
___
*[`codeforlife/user/models/user.py` line 97 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRgJNkD-dktFiik__6:-NhRgJNl3ZHsYYZTx0Hl:bmwlgrd) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/models/user.py#L97)):*
> ```Python
>     @property
>     def developer(self):
>         return self.userprofile.developer
> ```

Don't think we need this



_Code quote:_
```Python
    @property
    def developer(self):
        return self.userprofile.developer
```
___
*[`codeforlife/user/serializers/__init__.py` line 5 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRgZt-E8HVm_uBgTEy:-NhRgZt-E8HVm_uBgTEz:b-haykcy) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/serializers/__init__.py#L5)):*
> ```Python
> from .teacher import TeacherSerializer
> from .user import UserSerializer
> from .school import SchoolSerializer
> ```

These aren't ordered it seems



_Code quote:_
```Python
from .klass import ClassSerializer
from .student import StudentSerializer
from .teacher import TeacherSerializer
from .user import UserSerializer
from .school import SchoolSerializer
```
___
*[`codeforlife/user/tests/views/test_school.py` line 9 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRhQjH-rzXQnblHJ1t:-NhRhQjH-rzXQnblHJ1u:bhb3wnz) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L9)):*
> ```Python
> from ...serializers import SchoolSerializer
> from ...views import SchoolViewSet
> from ...models import User, School, Teacher, Student, Class, UserProfile
> ```

Organise imports? Does it not order relative imports alphabetically?



_Code quote:_
```Python
import typing as t

from rest_framework import status
from rest_framework.permissions import IsAuthenticated

from ....tests import APITestCase, APIClient
from ...serializers import SchoolSerializer
from ...views import SchoolViewSet
from ...models import User, School, Teacher, Student, Class, UserProfile
```
___
*[`codeforlife/user/tests/views/test_school.py` line 90 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRhMNw350vIK5kK1u2:-NhRhMNw350vIK5kK1u3:b-615vr3) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L90)):*
> ```Python
>         - student: A school student.
>         - indy_student: A non-school student.
>     
> ```

Extra whitespaces
___
*[`codeforlife/user/tests/views/test_school.py` line 111 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRhhSEBBplSxrgrcJM:-NhRhhSEBBplSxrgrcJN:b-scht4o) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L111)):*
> ```Python
>     def test_retrieve__indy_student(self):
>         """
>         Independent student can not retrieve any school.
> ```

cannot
___
*[`codeforlife/user/tests/views/test_school.py` line 144 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRhsRP9Sdmny5CUae0:-NhRhsRP9Sdmny5CUae1:b-scht4o) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L144)):*
> ```Python
>     def test_retrieve__teacher__not_same_school(self):
>         """
>         Teacher can not retrieve a school they are not in.
> ```

cannot
___
*[`codeforlife/user/tests/views/test_school.py` line 154 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRhyro9PdPknt8dnlW:-NhRhyrp01fiKspLdQv4:b-j0jamr) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L154)):*
> ```Python
>         self._retrieve_school(
>             school,
>             status_code_assertion=status.HTTP_404_NOT_FOUND,
> ```

Why is this a 404 and not a 403?
___
*[`codeforlife/user/tests/views/test_school.py` line 159 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRi7nR-YybE7d-ysfu:-NhRi7nR-YybE7d-ysfv:b-scht4o) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L159)):*
> ```Python
>     def test_retrieve__student__not_same_school(self):
>         """
>         Student can not retrieve a school they are not in.
> ```

cannot
___
*[`codeforlife/user/tests/views/test_school.py` line 171 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRiA-Y3SQYh6DKUiuh:-NhRiA-Y3SQYh6DKUiui:b-gsac8b) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L171)):*
> ```Python
>         self._retrieve_school(
>             school,
>             status_code_assertion=status.HTTP_404_NOT_FOUND,
> ```

Same question here
___
*[`codeforlife/user/tests/views/test_user.py` line 179 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRiwJV9WM9BxwRt1-e:-NhRiwJV9WM9BxwRt1-f:b-scht4o) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L179)):*
> ```Python
>     def test_retrieve__student__teacher__same_school(self):
>         """
>         Student can not retrieve a teacher from the same school.
> ```

cannot
___
*[`codeforlife/user/tests/views/test_user.py` line 195 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRiz412WfdOwTHZp2y:-NhRiz412WfdOwTHZp2z:b8ucw5p) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L195)):*
> ```Python
>        [...]

2023-10-23 18:30 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17)* status: 27 of 38 files reviewed, 36 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/settings/django.py` line 127 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRcg8r4J0Sc3qXli7g:-NhRmdux8-qqGv-xEi7b:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/settings/django.py#L127)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Wrong Django version
</blockquote></details>

Done.
___
*[`codeforlife/user/models/user.py` line 97 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRgJNkD-dktFiik__6:-NhRn6y4DmydTzF5Dlv9:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/models/user.py#L97)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Don't think we need this
</blockquote></details>

Done.
___
*[`codeforlife/user/serializers/__init__.py` line 5 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRgZt-E8HVm_uBgTEy:-NhRnKYu3QaACOe6sRcV:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/serializers/__init__.py#L5)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

These aren't ordered it seems
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/views/test_school.py` line 9 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRhQjH-rzXQnblHJ1t:-NhRnQTQANsgYJlRBOwd:bqp8ddq) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L9)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Organise imports? Does it not order relative imports alphabetically?
</blockquote></details>

It does. It's my fault - I forgot to enable import sorting.
___
*[`codeforlife/user/tests/views/test_school.py` line 90 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRhMNw350vIK5kK1u2:-NhSn2Vr8I_UqcM715fo:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L90)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/views/test_school.py` line 111 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRhhSEBBplSxrgrcJM:-NhRnnh968ahAOuu9P7u:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L111)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

cannot
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/views/test_school.py` line 144 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRhsRP9Sdmny5CUae0:-NhRoFD1E9ATJdDKWwk8:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L144)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

cannot
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/views/test_school.py` line 154 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRhyro9PdPknt8dnlW:-NhS1Mm34N7jU701Uasp:bh02u5b) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L154)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why is this a 404 and not a 403?
</blockquote></details>

it's 404 not found because the queryset only contains schools the user has access to. Because this is an indy student,  they don't have access to any schools. Therefore the queryset is empty and the school they are requesting is not found in the queryset. 
___
*[`codeforlife/user/tests/views/test_school.py` line 159 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRi7nR-YybE7d-ysfu:-NhRoLzG5v2ogYWreeko:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L159)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

cannot
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/views/test_school.py` line 171 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRiA-Y3SQYh6DKUiuh:-NhS2ADAAvwY4pVMI3Oz:byr4ffv) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L171)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same question here
</blockquote></details>

see above
___
*[`codeforlife/user/tests/views/test_user.py` line 179 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRiwJV9WM9BxwRt1-e:-NhS2DLl5dB_zDxobloT:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L179)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

cannot
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/views/test_user.py` line 195 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRiz412WfdOwTHZp2y:-NhS2GB7901vYzPKEN2X:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L195)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why not 403
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/views/test_user.py` line 200 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRj15D9z4cgUPApnc3:-NhS2GSQEB5Fd1EBQGAK:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L200)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

cannot
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/views/test_user.py` line 216 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRj1vBCEadoUKUMld1:-NhS2GrP1OYgZ8S9S2-X:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L216)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why not 403?
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/views/test_user.py` line 221 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRj3otAHn7osf1Gnvo:-NhS2HC59CnrDTKR9sun:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L221)):*
<details><summa [...]

2023-10-23 20:30 UTC, faucomte97 requested changes
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17)* status: all files reviewed, 16 unresolved discussions (waiting on @SKairinos)

___
*[`codeforlife/tests/api.py` line 237 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhTACmp28JQgKML16V4:-NhTACmp28JQgKML16V5:btxqkqk) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/41d45e3859f058ad184a1a3f3d6882aa76429320/codeforlife/tests/api.py#L237)):*
> ```Python
>             # Cannot assert that 2 teachers are in the same class since a class
>             # can only have 1 teacher.
>             if not (user.teacher is not None and is_teacher):
> ```

I find this whole section pretty hard to read :confused: 
The repeated nots also make it hard to wrap my head around, let alone the other cases below.

Maybe simplify it if you can or add more comments maybe.
___
*[`codeforlife/user/tests/views/test_school.py` line 154 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRhyro9PdPknt8dnlW:-NhTB89dEAoXjfz5PfHW:b-ko74mm) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L154)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

it's 404 not found because the queryset only contains schools the user has access to. Because this is an indy student,  they don't have access to any schools. Therefore the queryset is empty and the school they are requesting is not found in the queryset.
</blockquote></details>

I thought the test was meant to test the permission classes no? If so wouldn't it make sense to check that the teacher can't retrieve a class that they shouldn't have permission to access as opposed to trying to retrieve nothing?
___
*[`codeforlife/user/tests/views/test_school.py` line 171 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRiA-Y3SQYh6DKUiuh:-NhTBL5FCSZKNO_Edeoo:b6u0yhw) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_school.py#L171)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

see above
</blockquote></details>

cf comment above
___
*[`codeforlife/user/tests/views/test_user.py` line 195 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRiz412WfdOwTHZp2y:-NhTBdUy-PuRUv-hA8aC:b-8az6p1) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L195)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Again
___
*[`codeforlife/user/tests/views/test_user.py` line 216 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRj1vBCEadoUKUMld1:-NhTBnN91D1bk_MBZNLQ:b-8az6p1) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L216)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Again
___
*[`codeforlife/user/tests/views/test_user.py` line 237 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRj4eB8JjzhajAuKLd:-NhTBp8W-BqL1sKKdqMT:b-8az6p1) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L237)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Again
___
*[`codeforlife/user/tests/views/test_user.py` line 258 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRj7AF5M0_8j-MO0uh:-NhTBqFrB5dlQx0ktqOz:b-8az6p1) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L258)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Again
___
*[`codeforlife/user/tests/views/test_user.py` line 279 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRjDcuEOhtnF7PWbem:-NhTBs3W96bRVHdmKjHk:b3kqk) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L279)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

!
___
*[`codeforlife/user/tests/views/test_user.py` line 300 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRjG0W0xsZXISFbNMV:-NhTBtDi2CR6E3JiwUWF:b2nhyrh) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L300)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

abc
___
*[`codeforlife/user/tests/views/test_user.py` line 369 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhRkBzo4KTC35q6esmN:-NhTCLkk-67GXsXRswzx:b-rsekb7) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/b9ae46daa840c1e49f0a379b208a3d7a066a8fa9/codeforlife/user/tests/views/test_user.py#L369)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

That would only get the teachers in that school. We need the school's teachers OR the school's students. This can be achieved with the "|" operator. It translates to "search for the desired user from the school teachers or school students"
</blockquote></details>

Could we still not replace `User.objects.filter(new_teacher__school=user.teacher.school)` with `user.teacher.school.teacher_school.all()` at least?
___
*[`codeforlife/user/tests/views/test_user.py` line 211 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhTBUOl4Lwn7Q-2KOca:-NhTBUOl4Lwn7Q-2KOcb:b-gsac8b) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/41d45e3859f058ad184a1a3f3d6882aa76429320/codeforlife/user/tests/views/test_user.py#L211)):*
> ```Python
>         self._retrieve_user(
>             other_user,
>             status_code_assertion=status.HTTP_404_NOT_FOUND,
> ```

Same question here
___
*[`codeforlife/user/tests/views/test_user.py` line 299 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhTBg8L8UqXOV2_dcbX:-NhTBg8L8UqXOV2_dcbY:b-80wp0l) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/41d45e3859f058ad184a1a3f3d6882aa76429320/codeforlife/user/tests/views/test_user.py#L299)):*
> ```Python
>         self._retrieve_user(
>             other_user,
>             status_code_assertion=status.HTTP_404_NOT_FOUND,
> ```

Same question
___
*[`codeforlife/user/tests/views/test_user.py` line 446 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17#-NhTBz0A0U4C4QVNE6KV:-NhTBz0A0U4C4QVNE6KW:b-80wp0l) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/41d45e3859f058ad184a1a3f3d6882aa76429320/codeforlife/user/tests/views/test_user.py#L446)):*
> ```Python
>         self._retrieve_user(
>             other_user,
>             status_code_assertion=status.HTTP_404_NOT_FOUND,
> ```

Same question
___
*[`codeforlife/user/tests/views/test_user.py` line 466 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-py [...]

2023-10-24 10:46 UTC, faucomte97 approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)



<!-- Sent from Reviewable.io -->

2023-10-24 10:46 UTC, merged