feat: new data models
ocadotechnology/codeforlife-package-python pull request #28
Opened 2023-12-11 11:39 UTC by SKairinos

2023-12-15 02:49 UTC, faucomte97 requested changes
> Reviewed 37 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28)* status: 37 of 40 files reviewed, 23 unresolved discussions (waiting on @SKairinos)

___
*[`Pipfile` line 7 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldVF1t94skunQjVp49:-NldVF1t94skunQjVp4A:b-7eagqp) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/Pipfile#L7)):*
> ```TOML
> 
> [packages]
> django = "==3.2.20"
> ```

Optional, update to 3.2.23
___
*[`Pipfile` line 24 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldVCfc-Jl4ZUSX-P_T:-NldVCfc-Jl4ZUSX-P_U:b-y98zfh) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/Pipfile#L24)):*
> ```TOML
> aimmo = "==2.10.6" # TODO: remove
> rapid-router = "==5.11.3" # TODO: remove
> phonenumbers = "==8.12.12" # TODO: remove
> ```

All these should be removed too



_Code quote:_
```TOML
importlib-metadata = "==4.13.0" # TODO: remove. needed by old portal
django-formtools = "==2.2" # TODO: remove. needed by old portal
django-otp = "==1.0.2" # TODO: remove. needed by old portal
# https://pypi.org/user/codeforlife/
cfl-common = "==6.37.1" # TODO: remove
codeforlife-portal = "==6.37.1" # TODO: remove
aimmo = "==2.10.6" # TODO: remove
rapid-router = "==5.11.3" # TODO: remove
phonenumbers = "==8.12.12" # TODO: remove
```
___
*[`codeforlife/models/__init__.py` line 51 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldOnH67BkW1_yAC2kE:-NldOnH67BkW1_yAC2kF:b-fhhkkf) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/models/__init__.py#L51)):*
> ```Python
> 
>             Returns:
>                 The number of models updated.
> ```

The number of models matched, more so than the number of models "updated": https://docs.djangoproject.com/en/3.2/ref/models/querysets/#update
___
*[`codeforlife/models/__init__.py` line 57 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldQhIFDQ_AcCMCHt2F:-NldQhIFDQ_AcCMCHt2G:b-rm7mgf) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/models/__init__.py#L57)):*
> ```Python
>             return super().update(**kwargs)
> 
>         def delete(self, wait: t.Optional[timedelta] = None):
> ```

Having trouble understanding how this function works, maybe you can re-explain it to me.
___
*[`codeforlife/models/__init__.py` line 91 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldS2x2C519sTB60dZm:-NldS2x2C519sTB60dZn:b-hbrjoi) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/models/__init__.py#L91)):*
> ```Python
> 
>         def filter(self, *args, **kwargs):
>             """A stub that return our custom queryset."""
> ```

returns
___
*[`codeforlife/models/__init__.py` line 99 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldS6D2AvXnSm8wi7M5:-NldS6D2AvXnSm8wi7M6:b-hbrjoi) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/models/__init__.py#L99)):*
> ```Python
> 
>         def exclude(self, *args, **kwargs):
>             """A stub that return our custom queryset."""
> ```

returns
___
*[`codeforlife/models/__init__.py` line 107 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldSBUF5QfjXZTICiuw:-NldSBUF5QfjXZTICiux:b-hbrjoi) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/models/__init__.py#L107)):*
> ```Python
> 
>         def all(self):
>             """A stub that return our custom queryset."""
> ```

returns
___
*[`codeforlife/tests/model.py` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldUEcM7Aa2sHWc_TT7:-NldUEcM7Aa2sHWc_TT8:b-ayq7rx) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/tests/model.py#L30)):*
> ```Python
>         return t.get_args(cls.__orig_bases__[0])[  # type: ignore[attr-defined]
>             0
>         ]
> ```

Why this format?



_Code quote:_
```Python
        return t.get_args(cls.__orig_bases__[0])[  # type: ignore[attr-defined]
            0
        ]
```
___
*[`codeforlife/user/models/klass.py` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-Nlf9RaIAtM2NdXA3rWQ:-Nlf9RaIAtM2NdXA3rWR:byc5zbj) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/klass.py#L19)):*
> ```Python
> from . import school as _school
> from . import student as _student
> from . import teacher as _teacher
> ```

Two questions here I need you to remind me the answers for:
1. Why are you importing them as `_x`? Was it to avoid circular imports?
2. Where are these imports used? Is it in the typing strings only? If so, do you need to import them if it's only strings?



_Code quote:_
```Python
from . import school as _school
from . import student as _student
from . import teacher as _teacher
```
___
*[`codeforlife/user/models/otp_bypass_token.py` line 70 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NlfB1wh8YtV1kdSk5Gf:-NlfB1wh8YtV1kdSk5Gg:b11lxnh) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/otp_bypass_token.py#L70)):*
> ```Python
>                     + OtpBypassToken.objects.filter(
>                         user_id=user_id,
>                         delete_after__isnull=True,
> ```

Where does `delete_after` come from? This model doesn't extend `WarehouseModel`.
___
*[`codeforlife/user/models/otp_bypass_token.py` line 119 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NlfBLyE7aMtzmD3ElBI:-NlfBLyE7aMtzmD3ElBJ:b-pjpp9v) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/otp_bypass_token.py#L119)):*
> ```Python
> 
>         Returns:
>             A boolean designating if the token is matches.
> ```

remove "is"
___
*[`codeforlife/user/models/school.py` line 36 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NlfCQK1A57erEo4ASfn:-NlfCQK2AGi4EjvTNr1e:b-rzuq7z) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/school.py#L36)):*
> ```Python
>     # Shortcuts for convenience.
>     Country = Country
>     UkCounty = UkCounty
> ```

Please re-explain theses shortcuts to me, I forgot what they do.



_Code quote:_
```Python
    # Shortcuts for convenience.
    Country = Country
    UkCounty = UkCounty
```
___
*[`codeforlife/user/models/student.py` line 27 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NlfF03H8syUz5XanVYG:-NlfF03H8syUz5XanVYH:b-yki3mp) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/student.py#L27)):*
> ```Python
>     # pylint: disable-next=missing-class-docstring
>     class Manager(WarehouseModel.Manager["Student"]):
>         def create(  # type: ignore[override]
> ```

Please run me through the process of those 4 create functions again because I don't understand a) why we're passing the auto gen password and b) why we're passing in student instances when we're [...]

2023-12-15 10:31 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28)* status: 37 of 40 files reviewed, 23 unresolved discussions (waiting on @faucomte97)

___
*[`Pipfile` line 7 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldVF1t94skunQjVp49:-Nlgmkig1P7vpNVsb2sE:b-pp8u2g) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/Pipfile#L7)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Optional, update to 3.2.23
</blockquote></details>

will update in my next PR
___
*[`Pipfile` line 24 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldVCfc-Jl4ZUSX-P_T:-Nlgmi2u0391dIJ3FbPp:bas68kd) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/Pipfile#L24)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

All these should be removed too
</blockquote></details>

I removed these in my next PR
___
*[`codeforlife/models/__init__.py` line 51 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldOnH67BkW1_yAC2kE:-Nlgn7Yx0X-G50MASF0v:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/models/__init__.py#L51)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

The number of models matched, more so than the number of models "updated": https://docs.djangoproject.com/en/3.2/ref/models/querysets/#update
</blockquote></details>

Done.
___
*[`codeforlife/models/__init__.py` line 57 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldQhIFDQ_AcCMCHt2F:-NlgnGWA2MGHYjhdMoQZ:bo1oe64) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/models/__init__.py#L57)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Having trouble understanding how this function works, maybe you can re-explain it to me.
</blockquote></details>

By default, deleting warehouse models only schedules them for deletion by setting delete_after. You need to specify how long to wait before the data is actually deleted (schedule = now + wait). You can set a class-level default for the delete's wait timedelta (delete_wait). Or you can set it when calling delete in case you don't want to the default. Finally, if you want to actually delete (and not just schedule it), you call .delete(wait=timedelta()). The empty timedelta means your wait is basically 0 (there is no wait)
___
*[`codeforlife/models/__init__.py` line 91 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldS2x2C519sTB60dZm:-Nlgo6Wt7Qx0vaFDMsT0:b-h1fgnv) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/models/__init__.py#L91)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

returns
</blockquote></details>

fixed in my next PR
___
*[`codeforlife/models/__init__.py` line 99 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldS6D2AvXnSm8wi7M5:-Nlgo9XmDBqdGuvKX39d:b-h1fgnv) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/models/__init__.py#L99)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

returns
</blockquote></details>

fixed in my next PR
___
*[`codeforlife/models/__init__.py` line 107 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldSBUF5QfjXZTICiuw:-Nlgo8ae4uJEpsngxvEC:b-h1fgnv) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/models/__init__.py#L107)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

returns
</blockquote></details>

fixed in my next PR
___
*[`codeforlife/tests/model.py` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldUEcM7Aa2sHWc_TT7:-NlgoBBNAe2FFMYaEAxk:b3o7x4a) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/tests/model.py#L30)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why this format?
</blockquote></details>

Agreed its weird but that's how black does it. The formaters, linters and type-checkers sometimes want weird things.
___
*[`codeforlife/user/models/klass.py` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-Nlf9RaIAtM2NdXA3rWQ:-NlgoR2S22LiA1fDvnw_:b8iky3o) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/klass.py#L19)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Two questions here I need you to remind me the answers for:
1. Why are you importing them as `_x`? Was it to avoid circular imports?
2. Where are these imports used? Is it in the typing strings only? If so, do you need to import them if it's only strings?
</blockquote></details>

Question 1: Good question! I used private imports to:

1. discourage importing sub imports. for example, you shouldn't do this:
from codeforlife.user.models.teacher import user
instead it's private to communicate you shouldn't do this
from codeforlife.user.models.teacher import _user

2. it allows me to reuse the models name for a variable name, instead of it already being used as a package name. for exanmple:
from . import user as _user
user = _user.User.objects.get(pk=1)

Question 2

In this case, yes, it's only used for type hinting. Yes, we still need to import the modules even if it's only used in string-based type hints. The python interpreter still needs the imports to follow the references. It's just by wrapping them in strings, you're lazy-loading the type hints at the end instead of order of execution.
___
*[`codeforlife/user/models/otp_bypass_token.py` line 70 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NlfB1wh8YtV1kdSk5Gf:-NlgqAT7642c0uu53vJB:b7gw1v9) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/otp_bypass_token.py#L70)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Where does `delete_after` come from? This model doesn't extend `WarehouseModel`.
</blockquote></details>

Done. It was a mistake!
___
*[`codeforlife/user/models/otp_bypass_token.py` line 119 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NlfBLyE7aMtzmD3ElBI:-NlgqZ0kD0-bM_QUI4ED:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/otp_bypass_token.py#L119)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

remove "is"
</blockquote></details>

Done.
___
*[`codeforlife/user/models/school.py` line 36 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NlfCQK1A57erEo4ASfn:-NlgqZo21XuCT_DDMoST:by0nqam) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/school.py#L36)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Please re-explain theses shortcuts to me, I f [...]

2023-12-15 10:34 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28)* status: 37 of 40 files reviewed, 23 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/user/models/user.py` line 192 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NlfKyaW3DXVfkASKdjE:-Nlh1Xyg0fvHlGatnAhL:bars2ai) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/user.py#L192)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

You are right to an extent. When making students independent, we shouldn't do

student.delete(now=timedelta())

we should do:

user.student = None # NEED to make this none first!!
student.delete(now=timedelta()) # now user won't be cascade deleted
</blockquote></details>

correction:

user.student = None # NEED to make this none first!!  
user.save()
student.delete(now=timedelta()) # now user won't be cascade deleted


<!-- Sent from Reviewable.io -->

2023-12-15 12:27 UTC, faucomte97 requested changes
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28)* status: 36 of 40 files reviewed, 4 unresolved discussions (waiting on @SKairinos)

___
*[`codeforlife/models/__init__.py` line 57 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldQhIFDQ_AcCMCHt2F:-NlhRHFc40zD6PoIIW_9:b-3g4drd) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/models/__init__.py#L57)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

By default, deleting warehouse models only schedules them for deletion by setting delete_after. You need to specify how long to wait before the data is actually deleted (schedule = now + wait). You can set a class-level default for the delete's wait timedelta (delete_wait). Or you can set it when calling delete in case you don't want to the default. Finally, if you want to actually delete (and not just schedule it), you call .delete(wait=timedelta()). The empty timedelta means your wait is basically 0 (there is no wait)
</blockquote></details>

I'm still confused. I'm confused by the fact that the `delete` only happens if `wait == timedelta()` Where is the delete that happens if `wait` > `delete_after`?
___
*[`codeforlife/user/models/klass.py` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-Nlf9RaIAtM2NdXA3rWQ:-NlhOsFt7XJCYx9x5MFI:bxiekcz) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/klass.py#L19)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Question 1: Good question! I used private imports to:

1. discourage importing sub imports. for example, you shouldn't do this:
from codeforlife.user.models.teacher import user
instead it's private to communicate you shouldn't do this
from codeforlife.user.models.teacher import _user

2. it allows me to reuse the models name for a variable name, instead of it already being used as a package name. for exanmple:
from . import user as _user
user = _user.User.objects.get(pk=1)

Question 2

In this case, yes, it's only used for type hinting. Yes, we still need to import the modules even if it's only used in string-based type hints. The python interpreter still needs the imports to follow the references. It's just by wrapping them in strings, you're lazy-loading the type hints at the end instead of order of execution.
</blockquote></details>

But then, why not just import `User` for example so you could do `user = User.objects.get(pk=1)`, which is cleaner?
___
*[`codeforlife/user/models/user.py` line 149 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NlfKa301yBhgeh9sWzk:-NlhQKAQ6Ft0em7mvU2g:b-cqlf6k) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/user.py#L149)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

No. A user can be inactive but still retained. For example, you create your account but haven't verified your email. We only delete your account if is_active=False and last_login > 3 years ago.
</blockquote></details>

Why don't we just use `is_active` to check for email verification and `last_login` for account deletion? We don't need to set `is_active` to False again if `last_login` is over 3 years.
___
*[`codeforlife/user/models/user.py` line 200 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NlfLWP-A2KO2OfnAahc:-NlhR6c017kEe_r6cHq1:b-c24aal) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/user.py#L200)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

awesome! Thank you for sharing! will keep in mind for the future
</blockquote></details>

Still need to do


<!-- Sent from Reviewable.io -->

2023-12-15 16:15 UTC, faucomte97 reviewed
> Reviewed 1 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28)* status: 37 of 40 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-15 16:49 UTC, faucomte97 requested changes
> Reviewed 3 of 40 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28)* status: all files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`codeforlife/user/tests/models/test_user.py` line 168 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NliMEUY23kqPXVHBUpn:-NliMEUY23kqPXVHBUpo:bel9xbe) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/33d8e8bbd33f5e6725fd8e80fb7e93cbe0bb595b/codeforlife/user/tests/models/test_user.py#L168)):*
> ```Python
>             User.objects.create_user(
>                 password="password",
>                 first_name="teacher",
> ```

I know it doesn't really matter but let's put Indiana here or independent
___
*[`codeforlife/user/tests/models/test_user.py` line 266 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NliM_0O7d5biIx2PTgF:-NliM_0O7d5biIx2PTgG:bt6iudl) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/33d8e8bbd33f5e6725fd8e80fb7e93cbe0bb595b/codeforlife/user/tests/models/test_user.py#L266)):*
> ```Python
>         assert user.is_superuser
> 
>     def test_objects__create_superuser__student(self):
> ```

Actually that reminds of something. Do we want to allow for students (of any kind) to be superusers? So far we've only ever had Teacher objects for our superuser accounts, mainly because they also require 2FA to access the admin. Do we want to remove the functionality to create student superusers?


<!-- Sent from Reviewable.io -->

2023-12-15 17:20 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28)* status: 37 of 40 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/models/__init__.py` line 57 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NldQhIFDQ_AcCMCHt2F:-Nli8wNKEy26f5mg-XAb:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/models/__init__.py#L57)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I'm still confused. I'm confused by the fact that the `delete` only happens if `wait == timedelta()` Where is the delete that happens if `wait` > `delete_after`?
</blockquote></details>

Done.
___
*[`codeforlife/user/models/klass.py` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-Nlf9RaIAtM2NdXA3rWQ:-Nli94X3CiDi3Z1nf4Qe:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/klass.py#L19)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

But then, why not just import `User` for example so you could do `user = User.objects.get(pk=1)`, which is cleaner?
</blockquote></details>

Done.
___
*[`codeforlife/user/models/user.py` line 149 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NlfKa301yBhgeh9sWzk:-Nli983PDBJ2EeJFgpHR:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8f1f2b30edb4b87f8d4f12836d6072a8dc9fc49b/codeforlife/user/models/user.py#L149)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why don't we just use `is_active` to check for email verification and `last_login` for account deletion? We don't need to set `is_active` to False again if `last_login` is over 3 years.
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/models/test_user.py` line 168 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NliMEUY23kqPXVHBUpn:-NliUUEC3hUdjJNN5PzU:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/33d8e8bbd33f5e6725fd8e80fb7e93cbe0bb595b/codeforlife/user/tests/models/test_user.py#L168)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I know it doesn't really matter but let's put Indiana here or independent
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/models/test_user.py` line 266 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28#-NliM_0O7d5biIx2PTgF:-NliUUcpAn2emrwdVAEf:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/33d8e8bbd33f5e6725fd8e80fb7e93cbe0bb595b/codeforlife/user/tests/models/test_user.py#L266)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Actually that reminds of something. Do we want to allow for students (of any kind) to be superusers? So far we've only ever had Teacher objects for our superuser accounts, mainly because they also require 2FA to access the admin. Do we want to remove the functionality to create student superusers?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-15 17:21 UTC, faucomte97 approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/28)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)



<!-- Sent from Reviewable.io -->

2023-12-18 10:29 UTC, closed without merging

2023-12-18 10:29 UTC, SKairinos commented
will reopen when ready to merge