feat: Create base password validator per user type
ocadotechnology/codeforlife-package-python pull request #64
Opened 2024-01-29 18:38 UTC by faucomte97

2024-01-30 11:33 UTC, SKairinos requested changes
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64)* status: 1 of 7 files reviewed, 31 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/settings/django.py` line 107 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpOyFy8BJRSkjQ5CzXi:-NpOyFy8BJRSkjQ5CzXj:b5ugfl) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/settings/django.py#L107)):*
> ```Python
> 
> # TODO: replace with custom validators:
> # codeforlife.user.auth.password_validators.CommonPasswordValidator
> ```

Do we still need a custom common-password validator if django includes one out the box?
___
*[`codeforlife/settings/django.py` line 116 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpOxvqd3RB93m-rqxJp:-NpOxvqeAilUJ1F1VZIp:b8h6is9) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/settings/django.py#L116)):*
> ```Python
>     },
>     {
>         "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
> ```

Don't think we need the numeric validator.
From django docs: "checks whether the password isn’t entirely numeric."
We already do this in our custom validators.
___
*[`codeforlife/user/auth/password_validators/__init__.py` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpOymQoBP8hYVYyDsyZ:-NpOymQoBP8hYVYyDsy_:b-ifirlz) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/__init__.py#L1)):*
> ```Python
> from .dependent_student import DependentStudentPasswordValidator
> ```

add module docstring
___
*[`codeforlife/user/auth/password_validators/__init__.py` line 2 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpOz5F2-2evZP4R344T:-NpOz5F2-2evZP4R344U:b-s56nnh) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/__init__.py#L2)):*
> ```Python
> from .dependent_student import DependentStudentPasswordValidator
> from .independent_student import IndependentStudentPasswordValidator
> ```

now that we've remodelled the data, let's use the following terminology to denote our 3 user types:
teacher - self explanatory
student - this will only ever refer to a school student
independent - this will only ever refer to an independent learner. We can use "indy" for short variable names (but not class/function names)
___
*[`codeforlife/user/auth/password_validators/dependent_student.py` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpOypwmD6Icb_oAt4Qi:-NpOypwmD6Icb_oAt4Qj:bcfewmn) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/dependent_student.py#L1)):*
> ```Python
> from django.core.exceptions import ValidationError
> ```

add module docstring and rename file to student.py
___
*[`codeforlife/user/auth/password_validators/dependent_student.py` line 4 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpOzkyd48vanbYSbqnP:-NpOzkyd48vanbYSbqnQ:b-p270t8) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/dependent_student.py#L4)):*
> ```Python
> 
> 
> class DependentStudentPasswordValidator:
> ```

Rename to StudentPasswordValidator
___
*[`codeforlife/user/auth/password_validators/dependent_student.py` line 7 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP0Lc26WX9sKQ9DQrx:-NpP0Lc26WX9sKQ9DQry:b1vfxbr) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/dependent_student.py#L7)):*
> ```Python
>     def __init__(self):
>         self.min_length = 6
>         self.help_text = (
> ```

use the gettext util
"from django.utils.translation import gettext as _"
See example: https://docs.djangoproject.com/en/3.2/topics/auth/passwords/#writing-your-own-validator
___
*[`codeforlife/user/auth/password_validators/dependent_student.py` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP1LgU5WQzXAwCmPy4:-NpP1LgU5WQzXAwCmPy5:b3mrl9d) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/dependent_student.py#L11)):*
> ```Python
>         )
> 
>     def validate(self, password, user=None):
> ```

1. create a base password validator in base.py
2. defined method signature for validate() and add type hints for arguments. raise a NotImplementedError() in the base.validate
3. inherit base validator here.
4. ...
5. profit
___
*[`codeforlife/user/auth/password_validators/dependent_student.py` line 13 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP6V7J8p3KFwywF2Na:-NpP6V7J8p3KFwywF2Nb:b-k84tvm) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/dependent_student.py#L13)):*
> ```Python
>     def validate(self, password, user=None):
>         if len(password) < self.min_length:
>             raise ValidationError(self.help_text, code="password_not_valid")
> ```

code="password_too_short"
___
*[`codeforlife/user/auth/password_validators/independent_student.py` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP0mEVBwDEKPUDKn2Z:-NpP0mEVBwDEKPUDKn2_:b-pkqicw) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/independent_student.py#L1)):*
> ```Python
> import re
> ```

add module docstring and rename file to independent.py
___
*[`codeforlife/user/auth/password_validators/independent_student.py` line 6 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP0o3O6Yifc5-WrwV1:-NpP0o3O6Yifc5-WrwV2:b-w7gl0b) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/independent_student.py#L6)):*
> ```Python
> 
> 
> class IndependentStudentPasswordValidator:
> ```

rename to IndependentPasswordValidator
___
*[`codeforlife/user/auth/password_validators/independent_student.py` line 9 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP0tzsCDEQ6rMqC599:-NpP0tzsCDEQ6rMqC59A:bc0myrh) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/independent_student.py#L9)):*
> ```Python
>     def __init__(self):
>         self.min_length = 8
>         self.help_text = (
> ```

use gettext util
___
*[`codeforlife/user/auth/password_validators/independent_student.py` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP41y95OpQvsjwgyoQ:-NpP41y95OpQvsjwgyoR:bx7cc86) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/independent_student.py#L11)):*
> ```Python
>         self.help_text = (
>             f"Your password must contain at least {self.min_length} characters, 1 uppercase character, "
>             f"1 lowercase character and 1 digit.",
> ```

you've made this a tuple of stri [...]

2024-01-30 11:39 UTC, SKairinos requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64)* status: 1 of 7 files reviewed, 34 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/user/auth/password_validators/dependent_student.py` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP9eCm874hgEC5J8Pe:-NpP9eCm874hgEC5J8Pf:bulw4ly) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/dependent_student.py#L12)):*
> ```Python
> 
>     def validate(self, password, user=None):
>         if len(password) < self.min_length:
> ```

you need to check user type
___
*[`codeforlife/user/auth/password_validators/independent_student.py` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP9hNf9te0BGbZ13j_:-NpP9hNf9te0BGbZ13ja:bulw4ly) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/independent_student.py#L15)):*
> ```Python
> 
>     def validate(self, password, user=None):
>         if not (
> ```

you need to check user type
___
*[`codeforlife/user/auth/password_validators/teacher.py` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP9iB-0WzWbkOiEPsE:-NpP9iB-0WzWbkOiEPsF:bulw4ly) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/teacher.py#L15)):*
> ```Python
> 
>     def validate(self, password, user=None):
>         if not (
> ```

you need to check user type


<!-- Sent from Reviewable.io -->

2024-01-30 12:54 UTC, SKairinos reviewed
> Reviewed 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64)* status: 1 of 7 files reviewed, 25 unresolved discussions (waiting on @faucomte97)



<!-- Sent from Reviewable.io -->

2024-01-30 14:36 UTC, SKairinos requested changes
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64)* status: 2 of 7 files reviewed, 22 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/settings/django.py` line 107 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpOyFy8BJRSkjQ5CzXi:-NpPjXBQ05Xu1IAuJsZA:bwbyxmv) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/settings/django.py#L107)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I was wondering that, I guess we could have a deeper look and see exactly how it works maybe, but I should think we can trust it.
If for some reason we want to keep our custom common password validator (with the logic to ping [pwnd](https://haveibeenpwned.com/Passwords) then we can, but needs more investigation I'd say).
</blockquote></details>

modify todo


<!-- Sent from Reviewable.io -->

2024-01-30 19:28 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64)* status: 2 of 12 files reviewed, 22 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`codeforlife/settings/django.py` line 107 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpOyFy8BJRSkjQ5CzXi:-NpPphRGBLGcSfAIwfrq:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/settings/django.py#L107)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

modify todo
</blockquote></details>

Done.
___
*[`codeforlife/user/auth/password_validators/teacher.py` line 10 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP1DOlAQua8o-X-p3z:-NpQVke_9PYWyh5se5MH:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/teacher.py#L10)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Black didn't automatically change this - am I supposed to manually keep track?
</blockquote></details>

Done.
___
*[`codeforlife/user/auth/password_validators/teacher.py` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP4oqtA2rGfSVRwH6Y:-NpQVjtx-AMPcFnjULEc:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/teacher.py#L11)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Cf comment above
</blockquote></details>

Done.
___
*[`codeforlife/user/auth/password_validators/teacher.py` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP1I5L97jzV1p5LTke:-NpQViIh1QulKWP0nfKR:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/teacher.py#L14)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

see previous comment about adding a base validator
</blockquote></details>

Done.
___
*[`codeforlife/user/auth/password_validators/teacher.py` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP9iB-0WzWbkOiEPsE:-NpQVj6a-xbEV3CsI-_U:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/teacher.py#L15)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same question as before
</blockquote></details>

Done.
___
*[`codeforlife/user/auth/password_validators/teacher.py` line 22 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP74yJ5cDQPUonV4Ph:-NpQabVr9pDoc192ggHT:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/teacher.py#L22)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

on second thought, let's split this into multiple if checks. for each, raise a specific error message as to why that specific if check failed and give each a unique error code. This will give pointed help text to the user but more importantly, allow us to unit test specific error codes.
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/auth/password_validators/test_password_validators.py` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP5rTl2oAXhasRCj2k:-NpQVrbN1UM-xy0YFiII:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/tests/auth/password_validators/test_password_validators.py#L1)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

no need to import pytest. django's test case provides all the helper functions you require. just do self.helperNameHere()
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/auth/password_validators/test_password_validators.py` line 13 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP7Wlx6Mj4UDJz-jU-:-NpQpC2wBSLBsp2jvt-B:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/tests/auth/password_validators/test_password_validators.py#L13)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I'm a bit fuzzy on this, what's the difference / benefit of this?
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/auth/password_validators/test_password_validators.py` line 26 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP7u9UBnHdSdndF18c:-NpQpCfv9EGE5Y5boi1w:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/tests/auth/password_validators/test_password_validators.py#L26)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

create a unit_test per error code with naming convention:
test_validate__{error_code}
for example:
test_validate__password_too_short(self):
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/auth/password_validators/test_password_validators.py` line 32 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP5jb2DP1PoWxSwjRC:-NpQpDTn789FF68IsLzv:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/tests/auth/password_validators/test_password_validators.py#L32)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

why not, aren't list comprehensions preferred when possible?
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/auth/password_validators/test_password_validators.py` line 33 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP79DxB-vtfN-jComV:-NpQpEON4QUX6g-2pLyE:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/tests/auth/password_validators/test_password_validators.py#L33)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

we need to assert the specific error code raised to make sure the validation failed for the right reason.
</blockquote></details>

Done.
___
*[`codeforlife/user/auth/password_validators/dependent_student.py` line 7 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP0Lc26WX9sKQ9DQrx:-NpQVmn41419pDkqNR_y:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/dependent_student.py#L7)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

We've never really cared about translation strings, are we planning on doing this going forward then?
</blockquote></details>

Done.
___
*[`codeforlife/user/auth/password_validators/dependent_student.py` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpP1LgU5WQzXAwCmPy4:-NpQVmAI40bH6R-4fYEe:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/3b8b5c54ac749d3268823608b204c776cb5a0de0/codeforlife/user/auth/password_validators/dependent_student.py# [...]

2024-01-31 17:26 UTC, SKairinos requested changes
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64)* status: all files reviewed, 10 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/user/auth/password_validators/base.py` line 11 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVWJAp5bvdC8Wt7MJe:-NpVWJAp5bvdC8Wt7MJf:b-ap4j83) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/auth/password_validators/base.py#L11)):*
> ```Python
> 
> 
> class BasePasswordValidator:
> ```

rename to just "PasswordValidator" and add a one-liner class-docstring explain it's a base class
___
*[`codeforlife/user/auth/password_validators/teacher.py` line 16 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVWF_j4EvCCguJ3wIk:-NpVWF_j4EvCCguJ3wIl:b-k7ohz) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/auth/password_validators/teacher.py#L16)):*
> ```Python
> class TeacherPasswordValidator(BasePasswordValidator):
>     def __init__(self):
>         self.min_length = 10
> ```

remove init and put variable directly in validate()
___
*[`codeforlife/user/tests/auth/password_validators/password_validator.py` line 1 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVWn7kBJlKPS6w492R:-NpVWn7kBJlKPS6w492S:bbsngvc) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/tests/auth/password_validators/password_validator.py#L1)):*
> ```Python
> """
> ```

rename file to base.py
___
*[`codeforlife/user/tests/auth/password_validators/password_validator.py` line 38 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVWk9H1XGJRJyuZ3ZR:-NpVWk9H1XGJRJyuZ3ZS:b-9fum3u) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/tests/auth/password_validators/password_validator.py#L38)):*
> ```Python
>             def __exit__(self, *args, **kwargs):
>                 value = self.context.__exit__(*args, **kwargs)
>                 print(self.context)
> ```

remove print
___
*[`codeforlife/user/tests/auth/password_validators/test_independent.py` line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVXHeM7Ja95EXR69GB:-NpVXHeN3rRO00dfjQj-:bmtrnvy) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/tests/auth/password_validators/test_independent.py#L14)):*
> ```Python
>     @classmethod
>     def setUpClass(cls):
>         cls.user = User.objects.filter(
> ```

"assert cls.user is not None"
need to check there is a first user 
___
*[`codeforlife/user/tests/auth/password_validators/test_student.py` line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVXmYACwZtDP_xnPzZ:-NpVXmYACwZtDP_xnPz_:b-fawjf2) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/tests/auth/password_validators/test_student.py#L14)):*
> ```Python
>     @classmethod
>     def setUpClass(cls):
>         cls.user = User.objects.filter(new_student__isnull=False).first()
> ```

"assert cls.user is not None"
need to check there is a first user
___
*[`codeforlife/user/tests/auth/password_validators/test_teacher.py` line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVYIBL-K16RHeM7Lpl:-NpVYIBL-K16RHeM7Lpm:b-fawjf2) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/tests/auth/password_validators/test_teacher.py#L14)):*
> ```Python
>     @classmethod
>     def setUpClass(cls):
>         cls.user = User.objects.first()
> ```

"assert cls.user is not None"
need to check there is a first user
___
*[`codeforlife/user/tests/auth/password_validators/test_teacher.py` line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVYQ4NDtEztTiaL8At:-NpVYQ4NDtEztTiaL8Au:btt9qvo) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/tests/auth/password_validators/test_teacher.py#L14)):*
> ```Python
>     @classmethod
>     def setUpClass(cls):
>         cls.user = User.objects.first()
> ```

cls.user = User.objects.filter(new_teacher__isnull=False).first()
___
*[`codeforlife/user/auth/password_validators/independent.py` line 16 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVW5D31w0i6KZCmtpA:-NpVW5D31w0i6KZCmtpB:b-k7ohz) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/auth/password_validators/independent.py#L16)):*
> ```Python
> class IndependentPasswordValidator(BasePasswordValidator):
>     def __init__(self):
>         self.min_length = 8
> ```

remove init and put variable directly in validate()
___
*[`codeforlife/user/auth/password_validators/student.py` line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVWEvH6fRYkRXwU_dk:-NpVWEvH6fRYkRXwU_dl:b-k7ohz) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/auth/password_validators/student.py#L14)):*
> ```Python
> class StudentPasswordValidator(BasePasswordValidator):
>     def __init__(self):
>         self.min_length = 6
> ```

remove init and put variable directly in validate()


<!-- Sent from Reviewable.io -->

2024-02-01 09:32 UTC, SKairinos requested changes
> Reviewed 5 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/user/auth/password_validators/base.py` line 15 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpYyieP4ssDl3wx7XLQ:-NpYyieP4ssDl3wx7XLR:b-uy8cpj) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/4c7797a9243a3e117c1541fe611b6a5f77311ea9/codeforlife/user/auth/password_validators/base.py#L15)):*
> ```Python
>     """Base class for all password validators"""
> 
>     # pylint: disable-next=missing-class-docstring
> ```

I think you meant: "# pylint: disable-next=missing-function-docstring"
___
*[`codeforlife/user/tests/auth/password_validators/test_independent.py` line 23 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpYzLpl9cQWnFngPQBF:-NpYzLpm5ifmouVZn-hX:blzpsrg) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/4c7797a9243a3e117c1541fe611b6a5f77311ea9/codeforlife/user/tests/auth/password_validators/test_independent.py#L23)):*
> ```Python
> 
>     def test_validate__password_too_short(self):
>         """Check password validator rejects too short password"""
> ```

Small thing but only pointing it out now since we'll be writing so many unit tests going forward.

There's no need to add pretext in each test description ("Checks password validator rejects") .

This is because it's clear what the test case is. I already know you're testing the "IndependentPasswordValidator" from the name of the test case class. 

Therefore, just describe what the unit is testing. In this example, something like """Password cannot be too short."""
___
*[`codeforlife/user/tests/auth/password_validators/test_student.py` line 21 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpZ-crPEaBtOqTho3SU:-NpZ-crPEaBtOqTho3SV:bpkd03b) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/4c7797a9243a3e117c1541fe611b6a5f77311ea9/codeforlife/user/tests/auth/password_validators/test_student.py#L21)):*
> ```Python
> 
>     def test_validate__password_too_short(self):
>         """Check password validator rejects too short password"""
> ```

see comment about removing pretext
___
*[`codeforlife/user/tests/auth/password_validators/test_teacher.py` line 21 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpZ-ktb0fZ3yRFgAWqn:-NpZ-ktb0fZ3yRFgAWqo:bpkd03b) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/4c7797a9243a3e117c1541fe611b6a5f77311ea9/codeforlife/user/tests/auth/password_validators/test_teacher.py#L21)):*
> ```Python
> 
>     def test_validate__password_too_short(self):
>         """Check password validator rejects too short password"""
> ```

see comment about removing pretext


<!-- Sent from Reviewable.io -->

2024-02-01 10:01 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64)* status: 8 of 12 files reviewed, 4 unresolved discussions (waiting on @SKairinos)

___
*[`codeforlife/user/auth/password_validators/base.py` line 11 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVWJAp5bvdC8Wt7MJe:-NpVYtPZ4fk0AmiNsFER:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/auth/password_validators/base.py#L11)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename to just "PasswordValidator" and add a one-liner class-docstring explain it's a base class
</blockquote></details>

Done.
___
*[`codeforlife/user/auth/password_validators/base.py` line 15 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpYyieP4ssDl3wx7XLQ:-NpZ5JkP4LfZg23sUJWs:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/4c7797a9243a3e117c1541fe611b6a5f77311ea9/codeforlife/user/auth/password_validators/base.py#L15)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

I think you meant: "# pylint: disable-next=missing-function-docstring"
</blockquote></details>

Done.
___
*[`codeforlife/user/auth/password_validators/teacher.py` line 16 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVWF_j4EvCCguJ3wIk:-NpVZltHCYs_i1dp4kY2:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/auth/password_validators/teacher.py#L16)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

remove init and put variable directly in validate()
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/auth/password_validators/test_independent.py` line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVXHeM7Ja95EXR69GB:-NpV_MrkEY06C-i84Cic:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/tests/auth/password_validators/test_independent.py#L14)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

"assert cls.user is not None"
need to check there is a first user
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/auth/password_validators/test_independent.py` line 23 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpYzLpl9cQWnFngPQBF:-NpZ6Ncx1ZXpKEcvkmyg:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/4c7797a9243a3e117c1541fe611b6a5f77311ea9/codeforlife/user/tests/auth/password_validators/test_independent.py#L23)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Small thing but only pointing it out now since we'll be writing so many unit tests going forward.

There's no need to add pretext in each test description ("Checks password validator rejects") .

This is because it's clear what the test case is. I already know you're testing the "IndependentPasswordValidator" from the name of the test case class. 

Therefore, just describe what the unit is testing. In this example, something like """Password cannot be too short."""
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/auth/password_validators/test_student.py` line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVXmYACwZtDP_xnPzZ:-NpV_GxG7Vb3La-1X8IR:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/tests/auth/password_validators/test_student.py#L14)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

"assert cls.user is not None"
need to check there is a first user
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/auth/password_validators/test_student.py` line 21 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpZ-crPEaBtOqTho3SU:-NpZ6PNACcAOHxMY9gdv:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/4c7797a9243a3e117c1541fe611b6a5f77311ea9/codeforlife/user/tests/auth/password_validators/test_student.py#L21)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

see comment about removing pretext
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/auth/password_validators/test_teacher.py` line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVYIBL-K16RHeM7Lpl:-NpV_IEx8yfow5PmL9FE:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/tests/auth/password_validators/test_teacher.py#L14)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

"assert cls.user is not None"
need to check there is a first user
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/auth/password_validators/test_teacher.py` line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVYQ4NDtEztTiaL8At:-NpV_Lv_7lt4OS8qRRkx:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/tests/auth/password_validators/test_teacher.py#L14)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

cls.user = User.objects.filter(new_teacher__isnull=False).first()
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/auth/password_validators/test_teacher.py` line 21 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpZ-ktb0fZ3yRFgAWqn:-NpZ6N2p40YyDg3_ZPkc:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/4c7797a9243a3e117c1541fe611b6a5f77311ea9/codeforlife/user/tests/auth/password_validators/test_teacher.py#L21)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

see comment about removing pretext
</blockquote></details>

Done.
___
*[`codeforlife/user/auth/password_validators/independent.py` line 16 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVW5D31w0i6KZCmtpA:-NpVZGjLCNlSgQViKK89:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/auth/password_validators/independent.py#L16)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

remove init and put variable directly in validate()
</blockquote></details>

Done.
___
*[`codeforlife/user/auth/password_validators/student.py` line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVWEvH6fRYkRXwU_dk:-NpVZlCT4xMStsCWN_i5:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/auth/password_validators/student.py#L14)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

remove init and put variable directly in validate()
</blockquote></details>

Done.
___
*[`codeforlife/user/tests/auth/password_validators/password_validator.py` line 1 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64#-NpVWn7kBJlKPS6w492R:-NpVZqK5-7Pw_ZodO-6n:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/92ebe0c83e4e4063a349a46a3a56e82b9310bf2c/codeforlife/user/tests/auth/password_validators/password_v [...]

2024-02-01 10:04 UTC, SKairinos approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/64)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)



<!-- Sent from Reviewable.io -->

2024-02-01 10:04 UTC, merged